Portfolio Website: Finish Mobile Version
Megagig/My-Portfolio pull request #2
Opened 2023-03-25 19:09 UTC by Megagig

In this milestone, I implemented the following requirements
 I used html and css to create my portfolio website
 I installed linters configurations and made sure there are no linters error
 Build the work sections of the mobile website using the template chosen in the previous step.

2023-03-25 19:24 UTC, MeqdamAlqudah requested changes
Hi @Megagig 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![image](https://user-images.githubusercontent.com/74744787/227737308-5267436e-3617-425f-8f99-821f595c7719.png)
## Highlights
:+1: semantic tags 
:+1: design

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- fixing the distance of behind the headline section by fixing the width of cards in the works section

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 19:24 UTC, MeqdamAlqudah commented on index.html
>      <link rel="stylesheet" href="Styles.css" />
- [ ] Please make sure that the background of the toolbar section matches the design currently there is a difference between the background in the design and in your code.
Figma
![image](https://user-images.githubusercontent.com/74744787/227737230-f3cef7fa-9dfc-40c7-a7b6-98400ac4c10c.png)
Your design 
![image](https://user-images.githubusercontent.com/74744787/227737246-2c9b91dd-45b0-4073-8a70-46e8f2c009d6.png)

2023-03-25 19:24 UTC, MeqdamAlqudah commented on index.html
>      <title>Portfolio Website:Anthony</title>
- [ ] Please fix this weird space behind the headline section.
![image](https://user-images.githubusercontent.com/74744787/227737273-e15d0a66-1653-415a-a996-f8aa4e7d2f33.png)

2023-03-25 21:09 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Megagig , |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media4.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/> |

## Highlights

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 21:09 UTC, joskalenda commented on index.html
>      <title>Portfolio Website:Anthony</title>
- [ ] This issue is not fixed yet, please take time to address all the required changes the previous reviewer mentioned
<img width="407" alt="1" src="https://user-images.githubusercontent.com/77843050/227741645-d31a990f-5d60-412d-a4ce-5030045ee6d0.png">

2023-03-28 10:26 UTC, GedeonTS approved these changes
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @Megagig ,

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
 - No linter errors :+1: 
 - Good use of GitHub flow :+1: 
 - Responsive design :+1: 
## Optional suggestions :small_airplane: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 10:32 UTC, merged